The final assignment of time series


Rezvan Derayati


June 2020

Consider that the csv file that I am working on("current.csv") should be in the same folder that you run my jupyter file, since I have used the relative path when importing data. The csv file is in the rar file that I've sent to you.   

In [95]:
using CSV
using DataFrames
using Dates
using Statistics
using LinearAlgebra
using StatsBase
using Plots
using GLM
using PrettyTables
fredmd = CSV.File("current.csv", 
    datarow=3, 
    footerskip = 1, 
    dateformat = "mm/dd/yyyy",
    typemap = Dict(Int64=>Float64), 
    );


In [96]:
tcode = CSV.File("current.csv", datarow=2, limit = 1)[1];

fredmd = DataFrame(fredmd, copycols=true);

In [97]:
fredmd = fredmd[(fredmd[!, 1] .>= Date(1960, 1, 1)),:];

In this step, we creat a tuple of function for applying the transformation.

In [98]:
lag(x) = [missing; x[1:end-1]]
diff(x) = x .- lag(x)
diff2(x) = diff(diff(x))
logdiff(x) = log.(x) - log.(lag(x))
logdiff2(x) = diff(logdiff(x))
diffp(x) = diff(x./lag(x) .- 1.0)
logd(x) = log.(x)

## Create a tuple of functions
tfuns = (identity, diff, diff2, logd, logdiff, logdiff2, diffp)


(identity, diff, diff2, logd, logdiff, logdiff2, diffp)

This function transforms a single series (in a column vector) as specified by a given transfromation code i.e "tcode" that is reported in the original dataframe.

In [99]:
## Apply the transformation
for j in 2:size(fredmd, 2)
    trcode = tcode[j]
    @show j, trcode
    fredmd[!, j] = tfuns[trcode](fredmd[!, j])
    end;
#rimuoviamo le prime due osservazioni perse a causa della doppia differenza
fredmd=fredmd[3:end,:]

(j, trcode) = (2, 5)
(j, trcode) = (3, 5)
(j, trcode) = (4, 5)
(j, trcode) = (5, 5)
(j, trcode) = (6, 5)
(j, trcode) = (7, 5)
(j, trcode) = (8, 5)
(j, trcode) = (9, 5)
(j, trcode) = (10, 5)
(j, trcode) = (11, 5)
(j, trcode) = (12, 5)
(j, trcode) = (13, 5)
(j, trcode) = (14, 5)
(j, trcode) = (15, 5)
(j, trcode) = (16, 5)
(j, trcode) = (17, 5)
(j, trcode) = (18, 5)
(j, trcode) = (19, 5)
(j, trcode) = (20, 2)
(j, trcode) = (21, 2)
(j, trcode) = (22, 2)
(j, trcode) = (23, 5)
(j, trcode) = (24, 5)
(j, trcode) = (25, 2)
(j, trcode) = (26, 2)
(j, trcode) = (27, 5)
(j, trcode) = (28, 5)
(j, trcode) = (29, 5)
(j, trcode) = (30, 5)
(j, trcode) = (31, 5)
(j, trcode) = (32, 5)
(j, trcode) = (33, 5)
(j, trcode) = (34, 5)
(j, trcode) = (35, 5)
(j, trcode) = (36, 5)
(j, trcode) = (37, 5)
(j, trcode) = (38, 5)
(j, trcode) = (39, 5)
(j, trcode) = (40, 5)
(j, trcode) = (41, 5)
(j, trcode) = (42, 5)
(j, trcode) = (43, 5)
(j, trcode) = (44, 5)
(j, trcode) = (45, 5)
(j, trcode) = (46, 1)
(j, trcode) = (47,

721×129 DataFrame. Omitted printing of 125 columns
│ Row │ sasdate    │ RPI          │ W875RX1      │ DPCERA3M086SBEA │
│     │ Date       │ Float64?     │ Float64?     │ Float64?        │
├─────┼────────────┼──────────────┼──────────────┼─────────────────┤
│ 1   │ 1960-03-01 │ 0.00190976   │ 0.000917699  │ 0.0140716       │
│ 2   │ 1960-04-01 │ 0.00342582   │ 0.00362086   │ 0.0153824       │
│ 3   │ 1960-05-01 │ 0.00240288   │ 0.00244808   │ -0.0204166      │
│ 4   │ 1960-06-01 │ 0.000789293  │ -0.000248684 │ -0.000219455    │
│ 5   │ 1960-07-01 │ 0.00183214   │ 0.001905     │ 0.00202812      │
│ 6   │ 1960-08-01 │ -0.00162382  │ -0.00256846  │ -0.000931328    │
│ 7   │ 1960-09-01 │ 0.0012743    │ 0.000290318  │ 0.0047571       │
│ 8   │ 1960-10-01 │ 0.00295363   │ 0.00314661   │ 0.00484315      │
│ 9   │ 1960-11-01 │ -0.00429412  │ -0.00576251  │ -0.00348035     │
│ 10  │ 1960-12-01 │ -0.00456999  │ -0.00587955  │ -0.0123326      │
⋮
│ 711 │ 2019-05-01 │ 0.00121781   │ 0.000733245  │ 0.00339353      │
│ 712 │ 2019-06-01 │ 0.00241039   │ 0.00219651   │ 0.00207369      │
│ 713 │ 2019-07-01 │ -0.00244109  │ -0.00323603  │ 0.00309424      │
│ 714 │ 2019-08-01 │ 0.00374939   │ 0.00388198   │ 0.00233501      │
│ 715 │ 2019-09-01 │ 0.00221334   │ 0.00201326   │ 0.00176209      │
│ 716 │ 2019-10-01 │ -3.29885e-5  │ -0.00039666  │ 0.00067437      │
│ 717 │ 2019-11-01 │ 0.00456512   │ 0.00544033   │ 0.00236492      │
│ 718 │ 2019-12-01 │ -0.000497555 │ -7.04642e-5  │ 0.000991929     │
│ 719 │ 2020-01-01 │ 0.00455507   │ 0.0027374    │ 0.00270027      │
│ 720 │ 2020-02-01 │ 0.00468798   │ 0.0053406    │ 0.00135557      │
│ 721 │ 2020-03-01 │ -0.0195894   │ -0.0287466   │ -0.0692779      │

Working with DataFrame maybe inconvenient.

In [100]:
using Tables
## Z₀ are named tuples
Z = Tables.columntable(fredmd[:, 2:end]);

The EM algorithm is essentially the one given in the paper "Macroeconomic Forecasting Using Diffusion Indexes" by Stock & Watson [2002]. The algorithm is initialized by filling in missing values with the  unconditional mean of the series,which is zero since we standardaize dataframe; so that the panel is re-balanced. A T  ×  r matrix of factors F=(f 1 ,...,f 𝑡 )' and a N  ×  r matrix of loadigns  𝜆 =( 𝜆1 ,..., 𝜆𝑛 ) are estimated from this panel using the normalization that  𝜆 ' 𝜆 =I 𝑟 . The missing value for series i at time t is uptated from zero to  𝜆ℎ𝑎𝑡𝑖  𝑓ℎ𝑎𝑡𝑖 . This is multiplied by the standard deviation of the series and the mean is re-added. The resulting value considered as an observation for the series i at time t, and the mean and variance of the complete sample are calculated again. Demeaning & standardizing the updated dataset; estimating factors from this demeaned & standardized dataset & then using these factors to predict the dataset. The algorithm will  proceeds as follows: update missing values using values predicted by the latest set of factors; demean & standardize the updated dataset estimate a new set of factors using the demeaned & standardized updated dataset; & repeat the process until the factor estimates do not change.

The function recenter and rescale standardizes every series through substracting the mean and dividing by standard error.

In [101]:

function recenter_and_rescale(Z)
    statinfo = []
    X = []
    for i in eachindex(Z)
        Zi = Z[i]
        Zibar= mean(skipmissing(Zi))
        sigmaihat = std(skipmissing(Zi))
        info = (m = Zibar, s = sigmaihat)
        push!(statinfo, info)    
        push!(X, (Zi .- Zibar)./sigmaihat)
    end
    (X, statinfo)
end

recenter_and_rescale (generic function with 1 method)

In this step, I put a function for substituting missing values by zero.

In [102]:
function replace_missing(Z)
    X = copy(Z)
    for i in eachindex(Z)
        X[i][ismissing.(X[i])] .= 0.0
    end
    hcat(map(disallowmissing, X)...)
end

replace_missing (generic function with 2 methods)

This function replace missing data by prediction values.

In [103]:
function replace_missing(Z, fhat, lambdahat, statinfo)
    Znew = deepcopy(Z)
    for (j, i) in enumerate(keys(Z))
        m, s = statinfo[j]
        idx = ismissing.(Z[i])
        Znew[i][idx] .= s.*fhat[idx,:]*lambdahat[j,:] .+ m
    end
    return Znew
end

replace_missing (generic function with 2 methods)

In [104]:
function extract_and_fill(Z, r)    
    Xs, statinfo = recenter_and_rescale(Z);
    X = replace_missing(Xs)
    T, N = size(X)
    converged = false
    lambdahat = Array{Float64, 2}(undef, N, r)
    fhat = Array{Float64, 2}(undef, T, r)
    while !converged
        eignvv =  eigen(X'X./T); 
        idx = sortperm(eignvv.values, rev=true) 
        lambdahat .= sqrt(N)*eignvv.vectors[:, idx][:, 1:r] #loadings 
        fhat .= X*lambdahat./size(X, 2); 
        Z = replace_missing(Z, fhat, lambdahat, statinfo) 
        Xold = copy(X)        
        Xs, statinfo = recenter_and_rescale(Z);
        X = hcat(Xs...)
        converged = norm(Xold .- X, 2) < 1e-08 
    end
    return replace_missing(Z, fhat, lambdahat, statinfo), X, fhat, lambdahat
end


extract_and_fill (generic function with 1 method)

This function finds the index of minimum value for each column of a giving matrix. 

In [105]:
function minindc(x)

nrows=size(x,1)
ncols=size(x,2)

# Preallocate memory for output array
pos=zeros(ncols,1)

# Create column vector 1:nrows
seq=(1:nrows)'

# Find the index of the minimum value of each column in x
for i=1:ncols
    
    # Minimum value of column i
    min_i=minimum(x[:,i])
    
    # Column vector containing the row number corresponding to the minimum()
    # value of x[:,i] in that row & zeros elsewhere
    colmin_i= seq*((x[:,i].-min_i).==0)
    #println(colmin_i)
    # Produce an error if the minimum value occurs more than once
    if sum(colmin_i.>0)>1
        println("Minimum value occurs more than once.")
    end
    
    # Obtain the index of the minimum value by taking the sum of column
    # vector "colmin_i"
    pos[i]=sum(colmin_i)
    
end

pos = convert(Array{Int64}, pos)
end

minindc (generic function with 1 method)

I apply the PCp2  criterion developed in Bai and Ng (2002) so this function determines the number of factors to be selected for a given dataset using the second information criteria. 

In [106]:
function Baing(Z, r)
    out = extract_and_fill(Z, r);
    N = length(Z)
    T = length(Z[1])
    V = 0.0    
    σ2 = 0.0

    for t in 1:T     
        v= out[2][t,:] .- out[4]*out[3][t,:]
        V += v'v        
        σ2 += sum(v.^2)
    end
    penalty = (N+T)/(N*T)*log(min(N,T))
    σ2 = σ2/(N*T)
    return(log(V/(N*T)) + r*penalty)
end


Baing (generic function with 1 method)

In this step, I determine the max number of factors to be selected and then calculate the in following steps the best factor will be selected based on minimum value.

In [107]:
r=20
 baing=zeros(r,1)
for i in 1:r
   baing[i]=Baing(Z, i)
end
baing

20×1 Array{Float64,2}:
 -0.1153857166916281
 -0.1586113596841667
 -0.2061038016572318
 -0.24213369160686976
 -0.2647721021842269
 -0.2851182319478738
 -0.2958179423829575
 -0.2974434872027376
 -0.29502135577685434
 -0.29450764639555205
 -0.2912660307478345
 -0.2850960986160638
 -0.27804220789511247
 -0.2726907064146933
 -0.2667924008019693
 -0.2595338601448248
 -0.25363591700535826
 -0.24693253815771776
 -0.24107799301965227
 -0.23517560169141216

In [108]:
minindc(baing) #the output of this function shows the optimum number of factors

1×1 Array{Int64,2}:
 8

The criterion finds 8 factors in this sample, as in McCracken and Ng (2016). 

The model is: \begin{equation} \label{var}
\boldsymbol{X}_t=\boldsymbol{\lambda}(L)\boldsymbol{f}_{t}+ \boldsymbol{e}_t 
\end{equation}
\begin{equation} \label{var1}
\boldsymbol{f}_t=\boldsymbol{\psi}(L)\boldsymbol{f}_{t-1}+ \boldsymbol{\eta}_t
\end{equation}

In [109]:
Z8, X8, fhat8, lambdahat8 = extract_and_fill(Z, 8);

In following steps, I calculated the R_squared of the different regressions and report them in the following table. Moreover, we also report the marginal R_squared of factors; which represents the variability of the joint series the factor is able to explain. This incremental explanatory power of factor k is mR$^2_i$(k)= R$^2_i$(k)-R$^2_i$(k-1), k=2...r with mR$^2_i$(1)=R$^2_i$. The average importance of factor-k is mean of marginal R_squared for factor-k. I went through this procedure since the purpose is to define ten top series whose variability is mostly explained by each of 8 factors.

In [110]:
function r_squared(lambdahat,fhat,X)

N, r= size(lambdahat)

    R2 =[] #matrix of all r-squared of the model x_j=b*f_i
    R3 = [] #matrix of r-squared of the models x_j=b_1*f_1+...+b_i*f_i
    mR2 = [] #matrix of incremental r-squared of the factors
    mRmean = [] #mean of the marginal explanatory power of each factor (8 elements)
    mR=[]

    for j in 1:N, i in 1:r #we derive the matrix of r_squared of the model x_j=b*f_i
    ols=fhat[:,i]\X[:,j]
        R=sum((fhat[:,i]*ols.-mean(X[:,j])).^2)./sum((X[:,j].-mean(X[:,j])).^2)
    push!(R2,R)
    end
    
    for j in 1:N, i in 1:r #in this loop we derive the matrix of r-squared of the models x_j=b_1*f_1+...+b_i*f_i
        ols= fhat[:,1:i]\X[:,j]
        R=sum((fhat[:,1:i]*ols.-mean(X[:,j])).^2)./sum((X[:,j].-mean(X[:,j])).^2)
        push!(R3,R)
    end
    R4=reshape(R3,r,N)
     
    for j in 1:N, i in 1:r-1 #in this loop we derive the marginal increase 
        mR=R4[i+1,j]-R4[i,j]
        push!(mR2,mR)
    end
    mR2=reshape(mR2, r-1,N)
    mRfinal=vcat(R4[1,:]',mR2) #we add the first marginal r_squared which is the standard r_squared
   
    for i in 1:8 #we finally calculate the mean
    mR=mean(mRfinal[i,1:end])
    push!(mRmean,mR)
    end
    return R2, mRmean
end

R28, mRmean8=r_squared(lambdahat8,fhat8,X8)

(Any[0.1051758357453706, 0.019418655218245175, 0.013595746935574773, 0.019812829849370696, 0.01855007703613584, 0.0014853547978769623, 0.0040493485090491305, 0.029326293351024026, 0.17313566651914988, 0.033617108937025325  …  0.004940284042299794, 0.008834490779945121, 0.21523860313103468, 0.018727263978477827, 0.0014227750026383655, 0.011858374964510109, 0.0025264047527887063, 0.003069653452451971, 0.17519506055747633, 0.000987368420691075], Any[0.14630503791217486, 0.0719325115104497, 0.06876201333063982, 0.05509893778299316, 0.042995736901292776, 0.03869338073772955, 0.031016936818367317, 0.024788469152327314])

In [111]:
function top_ten(R2, N, r)
    
R2=reshape(R2,r,N)
R2=transpose(R2)
name=names(fredmd)[2:end] #adding names
U=hcat(name,R2)
    
A=[] #adding names in the values to create a tuple(value, name)
for i in 1:N, j in 2:r+1
    Ai=[U[i,j], U[i,:1]]
    push!(A,Ai)
end
B=reshape(A,r,N)

B=sort!(B,dims=2, rev=true) #sorting

top10=[] #taking top10 factors by r_squared
for i in 1:r
factori=B[i,1:10]
    push!(top10,factori)
end
top10=hcat(top10...)

top=[] #getting back to a standard table, easier to handle with
for i in 1:r, k in 1:2, j in 1:10
    t=top10[j,i][k]
    push!(top,t)
end
top=reshape(top,10,2*r)
    return top
    
end

top8=top_ten(R28,128,8)

10×16 Array{Any,2}:
 0.715493  "IPMANSICS"  0.743482  …  0.412762   "TWEXAFEGSMTHx"
 0.701591  "PAYEMS"     0.730176     0.267488   "EXSZUSx"
 0.684055  "INDPRO"     0.710746     0.247002   "EXUSUKx"
 0.664778  "USGOOD"     0.682174     0.169539   "EXJPUSx"
 0.6315    "IPFPNSS"    0.655081     0.14391    "CES0600000008"
 0.620097  "CUMFNS"     0.638294  …  0.129988   "CES3000000008"
 0.606266  "MANEMP"     0.626212     0.121023   "CONSPI"
 0.564089  "DMANEMP"    0.581694     0.118965   "NONREVSL"
 0.54578   "IPDMAT"     0.500361     0.0879441  "DTCTHFNM"
 0.539822  "IPFINAL"    0.479744     0.0783595  "IPNCONGD"

In [112]:
mRmean8

8-element Array{Any,1}:
 0.14630503791217486
 0.0719325115104497
 0.06876201333063982
 0.05509893778299316
 0.042995736901292776
 0.03869338073772955
 0.031016936818367317
 0.024788469152327314

In [113]:
@pt :header=["Factor 1" "Variable" "Factor 2" "Variable"; "mR^2=0.14631" "" "mR^2=0.07193" ""] top8[1:10,1:4] :header=["Factor 3" "Variable" "Factor 4" "Variable"; "mR^2= 0.06876" "" "mR^2= 0.05509" ""] top8[1:end,5:8] :header=["Factor 5" "Variable" "Factor 6" "Variable"; "mR^2= 0.04299" "" "mR^2=0.03869" ""] top8[1:10,9:12] :header=["Factor 7" "Variable" "Factor 8" "Variable"; "mR^2= 0.03102" "" "mR^2=0.02479" ""] top8[1:10,13:16];

┌────────────────────┬───────────┬────────────────────┬─────────────────┐
│           Factor 1 │  Variable │           Factor 2 │        Variable │
│       mR^2=0.14631 │           │       mR^2=0.07193 │                 │
├────────────────────┼───────────┼────────────────────┼─────────────────┤
│ 0.7154928511533396 │ IPMANSICS │ 0.7434815002390499 │     CUSR0000SAC │
│ 0.7015913634224793 │    PAYEMS │ 0.7301759557986232 │ DNDGRG3M086SBEA │
│ 0.6840546585111387 │    INDPRO │ 0.7107459949592869 │   CUSR0000SA0L2 │
│ 0.6647782015364798 │    USGOOD │ 0.6821741967191135 │        CPIAUCSL │
│ 0.6314995340028186 │   IPFPNSS │ 0.6550806685270908 │   CUSR0000SA0L5 │
│ 0.6200973834604547 │    CUMFNS │ 0.6382936158782815 │        CPITRNSL │
│ 0.6062664893721316 │    MANEMP │ 0.6262121035798989 │           PCEPI │
│ 0.5640886919127375 │   DMANEMP │ 0.5816937596267789 │        CPIULFSL │
│ 0.5457800963311819 │    IPDMAT │ 0.5003607041440007 │      WPSFD49502 │
│ 0.5398218413669652 │   IPFINAL │ 0.4

This table lists R$^2_{j}$ and the ten series with the highest mR$^2_{j}$ for factor j. Factor 1 explains 0.14631 of the variation in the data and can be interpreted as a real activity/employment factor since the mR$_i$ associated with the industrial production and employment series are around 0.7. Factor 2 has an mR$^2$(2) of 0.07193 and its explanatory power is concentrated on price variables and thus can be interpreted as an inflation factor.Factor 3 contributes to 0.06876 of the variation in the data and is dominated by forward-looking variables like interest rate spreads. Factor 4 can be interpreted as an interest rate factor and Factor 5 is a mix of housing and interest rate variables. Like factor 1, factor 6 concentrates on real variables. Factor 7 has explanatory power for stock market variables while factor 8 has explanatory power for exchange rates.

In this step, in order to choose the numbers of lags of both factors and INDPRO in our model, we construct a function computing the BIC. We considered up to 3 lags of the first factor and up to 6 lags of INDPRO using a sample from 01/06/1960 to 01/03/2020. It appears that the best model is the one with 3 lags of the factor and 3 lags of IP.

In [114]:
y_bic=[lead(fredmd[:,:INDPRO])...][6:end-1]
X_bic=[fhat8[:,:1] lag(fhat8[:,:1]) lag(lag(fhat8[:,:1])) lag(lag(lag(fhat8[:,:1])))][6:end-1,:]
Z_bic=[fredmd[:,:INDPRO] lag(fredmd[:,:INDPRO]) lag(lag(fredmd[:,:INDPRO])) lag(lag(lag(fredmd[:,:INDPRO]))) lag(lag(lag(lag(fredmd[:,:INDPRO])))) lag(lag(lag(lag(lag(fredmd[:,:INDPRO])))))][6:end-1,:];

In [115]:
## This function chooses the best model according to the BIC criterion
function best_model(y,X,Z)
    bic=[]
    T=size(X,1)
     y = convert(Vector{Float64}, y)
        X = convert(Matrix{Float64},X)
Z=convert(Matrix{Float64},Z)
    for i in 1:6, j in 1:4
        R=hcat(X[:,1:j], Z[:,1:i])
        ols=lm(R,y)
        rss=GLM.deviance(ols)
            bici=T*log(rss/T)+((j+i)*log(T))
            push!(bic,bici)
    end
    return bic
end

best_model (generic function with 1 method)

In [116]:
best_model(y_bic,X_bic,Z_bic);

 As next step,our goal is to forecast industrial production in the following six months. This can be done by running a regression of the lead of industrial production -INDPRO- on INDPRO itself and lagged values of it, as well as on the first factor and lagged values of it. Once INDPRO is leaded,  we have a missing value at the bottom of the vector, and so we can only regress on X$_{t-1}$; once coefficients estimates are obtained, we can compute the first step-ahead forecast of indpro as the product of the coefficients and X$_t$. In order to obtain the second-step ahead forecast, it is sufficient to insert the previous estimate of the lead of INDPRO in the original vector, and so recursively carrying out the procedure. The function below takes as arguments the regressors (XX), the regressand (y) and the number of step-ahead forecasts to be performed (s). The output will be the $\textit{s}$ steps-ahead forecasts.

In [117]:
XX = [fredmd[!,:INDPRO] lag(fredmd[!,:INDPRO]) lag(lag(fredmd[!,:INDPRO])) lag(lag(lag(fredmd[!,:INDPRO]))) fhat8[:,:1] lag(fhat8[:,:1]) lag(lag(fhat8[:,:1])) lag(lag(lag(fhat8[:,:1])))]
y= fredmd[!,:INDPRO];

In [118]:
function prediction(XX, y, s)
    XX_T=XX[end,:]
    XX=XX[4:end-1,:]
    yy=deepcopy(y)
    pred=[]
    for j in 1:s
        z=lead(yy)[3+j:end-1]
        z = convert(Vector{Float64}, z)
        XX = convert(Matrix{Float64},XX)
        coef=XX\z
        p=XX_T'*coef
    push!(pred,p)
        push!(yy,p)
    end
    return pred
end

prediction (generic function with 1 method)

Now I predict the first up to the sixth step-ahead forecasts of INDPRO. According to our initial transformation, the the values can be interpreted as annalized growth rate, once they are multiplied by 1200. As it can be seen, for instance, the first step-ahead shows that industrial production will decrease on annual basis of 27%, if we assume that the forecast of the monthly growth rate will be kept constant in the twelve months ahead.

In [119]:
prediction(XX, y, 6)*100*12

6-element Array{Float64,1}:
 -27.21589992940161
 -30.473622716086357
 -21.592768968028214
 -18.920990585142995
  -9.371697198378142
 -16.178084089320066

Finally it is the time to compare our predictive power of our model with an AR(3). This is done by calculating the MSE derived from an out-of-sample analysis with data from 01/01/1961 to 12/01/2019.

In [120]:
XX_sample=XX[13:end-5,:]; ##from 01/01/1961 to 12/01/2019##
y_sample=y[13:end-5,:]; ##from 01/01/1961 to 12/01/2019##

In [121]:
function out_of_sample(XX,y)
   error=[]
     for j in 1:140
        XX1=XX[j:563+j,:]
        XX1 = convert(Matrix{Float64},XX1)
        Ly=lead(y)[j:563+j]
        Ly = convert(Vector{Float64}, Ly)
        XX_T=XX[564+j,:]
        XX_T=convert(Vector{Float64},XX_T)
        coef=XX1\Ly
        pred=XX_T'*coef
        y_actual=y[564+j]
        pred_err=(y_actual-pred)^2
        push!(error, pred_err)
        end 
    MSE=mean(sum(error))
    return MSE
end

out_of_sample (generic function with 1 method)

In [122]:
#MSE of the first step-ahead model with the first factor and three lags of the first factor, and three lags of INDPRO
out_of_sample(XX_sample,y_sample)

0.005373720414960443

In [123]:
XX_sample;

In [124]:
XX_AR = [fredmd[!,:INDPRO] lag(fredmd[!,:INDPRO]) lag(lag(fredmd[!,:INDPRO])) lag(lag(lag(fredmd[!,:INDPRO])))]
y_AR= fredmd[!,:INDPRO];

In [125]:
XX_ARsample=XX_AR[13:end-5,:] ##from 01/01/1961 to 12/01/2019##
y_ARsample=y_AR[13:end-5,:]; ##from 01/01/1961 to 12/01/2019##

In [126]:
#MSE of AR(3)
out_of_sample(XX_ARsample,y_ARsample)

0.0036388062341942587

 Surprisingly, it turns out that the AR(3) is better at predicting INDPRO than our dynamic factor model. One of the explanation can be due that MSE is one creterion which is not completely reliable for evaluation of dominance of a model. Also we can not determine the preferred model just through the analyzing of one variable.